<a href="https://colab.research.google.com/github/Harin22/ml-data-preprocessing/blob/main/2026_QS_World_University_Rankings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Importing Libraries

In [1]:
import numpy as np
import pandas as pd
import sklearn as sk

In [5]:
df = pd.read_csv('2026_QS_World_University_Rankings[1].csv')
display(df.head())

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

### Extracting Basic info about the datasets

In [11]:
print("Shape:", df.shape)
display(df.describe())
display(df.head())

print(df.info())

Shape: (1501, 30)

,AR SCORE,ER SCORE,FSR SCORE,CPF SCORE,IFR SCORE,ISR SCORE,ISD SCORE,IRN SCORE,EO SCORE,SUS SCORE
count,1501.000000,1501.000000,1501.000000,1501.000000,1414.000000,1464.00000,1464.000000,1499.000000,1501.000000,1477.000000
mean,25.785943,26.944237,33.950433,30.425516,36.305658,33.32541,34.526981,53.356905,29.989674,51.254367
std,24.500905,25.504494,28.440071,29.679882,35.252024,32.75066,31.108600,28.920632,29.197573,21.266331
min,1.000000,1.000000,1.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,3.000000
25%,8.800000,8.500000,10.800000,6.000000,6.600000,5.90000,8.675000,27.500000,6.200000,35.700000
50%,16.000000,16.500000,23.500000,18.000000,20.100000,19.40000,21.700000,55.800000,17.900000,48.700000
75%,32.700000,37.500000,50.500000,49.700000,66.100000,56.70000,55.650000,78.500000,46.000000,66.500000
max,100.000000,100.000000,100.000000,100.000000,100.000000,100.00000,100.000000,100.000000,100.000000,100.000000

,2026 Rank,Previous Rank,Institution Name,Country/Territory,Region,Size,Focus,Research,Status,AR SCORE,...,ISR RANK,ISD SCORE,ISD RANK,IRN SCORE,IRN RANK,EO SCORE,EO RANK,SUS SCORE,SUS RANK,Overall SCORE
0,1,1,Massachusetts Institute of Technology (MIT),United States of America,Americas,M,CO,VH,Private not for Profit,100.0,...,153,92.3,130,94.1,98,100.0,7,93.8,33,100
1,2,2,Imperial College London,United Kingdom,Europe,L,FO,VH,Public,99.6,...,35,100.0,22,97.5,28,95.9,68,98.3,7=,99.4
2,3,6,Stanford University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,261,76.1,230,96.5,49,100.0,2,95.4,19=,98.9
3,4,3,University of Oxford,United Kingdom,Europe,L,FC,VH,Public,100.0,...,80,98.7,67,100.0,1,100.0,3,77.9,198=,97.9
4,5,4,Harvard University,United States of America,Americas,L,FC,VH,Private not for Profit,100.0,...,217,60.6,335,99.4,8,100.0,1,77.8,201=,97.7

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1501 entries, 0 to 1500
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   2026 Rank          1501 non-null   object
 1   Previous Rank      1389 non-null   object
 2   Institution Name   1501 non-null   object
 3   Country/Territory  1501 non-null   object
 4   Region             1501 non-null   object
 5   Size               1500 non-null   object
 6   Focus              1501 non-null   object
 7   Research           1500 non-null   object
 8   Status             1454 non-null   object
 9   AR SCORE           1501 non-null   float64
 10  AR RANK            1501 non-null   object
 11  ER SCORE           1501 non-null   float64
 12  ER RANK            1501 non-null   object
 13  FSR SCORE          1501 non-null   float64
 14  FSR RANK           1501 non-null   object
 15  CPF SCORE          1501 non-null   float64
 16  CPF RANK           1501 non-null   object
 17  IFR SCORE          1414 non-null   float64
 18  IFR RANK           1414 non-null   object
 19  ISR SCORE          1464 non-null   float64
 20  ISR RANK           1464 non-null   object
 21  ISD SCORE          1464 non-null   float64
 22  ISD RANK           1464 non-null   object
 23  IRN SCORE          1499 non-null   float64
 24  IRN RANK           1499 non-null   object
 25  EO SCORE           1501 non-null   float64
 26  EO RANK            1501 non-null   object
 27  SUS SCORE          1477 non-null   float64
 28  SUS RANK           1477 non-null   object
 29  Overall SCORE      1501 non-null   object
dtypes: float64(10), object(20)
memory usage: 351.9+ KB
None

In [15]:
if 'University of Birmingham' in df['Institution Name'].values:
    print("It exists.")
else:
    print("Does not exist.")

It exists.